ini_open(argument0);
	ini_write_string(argument1,"Name",argument2.name);
	ini_write_real(argument1,"Quantity",argument2.quantity);
	ini_write_real(argument1,"Quality",argument2.quality);
	ini_write_real(argument1,"Sprite",argument2.sprite);
	ini_write_string(argument1,"Innates", ds_map_write(argument2.innates));
	ini_write_string(argument1,"Attributes", ds_map_write(argument2.attributes));
	ini_write_string(argument1,"Equip Slot", argument2.applicableSlot);
	ini_write_string(argument1,"Stackable", argument2.stackable);
ini_close();